#pragma once

// #include "Animation/AnimationTexture.h"
// #include "Animation/Blending.h"
// #include "Animation/CCDSOlver.h"
// #include "Animation/Clip.h"
// #include "Animation/CrossFadeController.h"
// #include "Animation/CrossFadeTarget.h"
// #include "Animation/FABRIKSolver.h"
// #include "Animation/FastTrack.h"
// #include "Animation/Frame.h"
// #include "Animation/Interpolation.h"
// #include "Animation/Pose.h"
// #include "Animation/Skeleton.h"
// #include "Animation/Track.h"
// #include "Animation/TransformTrack.h"

#include "App.h"
#include "ImageData.h"
#include "Camera.h"
#include "Scene.h"
#include "Pass.h"
#include "InputSystem.h"
#include "Logger.h"
#include "Timer.h"
#include "Window.h"

#include "Graphics/VK/AS.h"
#include "Graphics/VK/Attachment.h"
#include "Graphics/VK/Buffer.h"
#include "Graphics/VK/CommandBuffer.h"
#include "Graphics/VK/CommandPool.h"
#include "Graphics/VK/DescriptorSet.h"
#include "Graphics/VK/DescriptorPool.h"
#include "Graphics/VK/DescriptorSetLayout.h"
#include "Graphics/VK/DescriptorTable.h"
#include "Graphics/VK/Device.h"
#include "Graphics/VK/Enum.h"
#include "Graphics/VK/Format.h"
#include "Graphics/VK/Framebuffer.h"
#include "Graphics/VK/Image.h"
#include "Graphics/VK/ImageView.h"
#include "Graphics/VK/Instance.h"
#include "Graphics/VK/Pipeline.h"
#include "Graphics/VK/PipelineLayout.h"
#include "Graphics/VK/Queue.h"
#include "Graphics/VK/RayTraceSBT.h"
#include "Graphics/VK/RenderPass.h"
#include "Graphics/VK/Sampler.h"
#include "Graphics/VK/Shader.h"
#include "Graphics/VK/ShaderGroup.h"
#include "Graphics/VK/SwapChain.h"
#include "Graphics/VK/SyncObject.h"

#include "Math/DualQuaternion.h"
#include "Math/Math.hpp"
#include "Math/Matrix2.h"
#include "Math/Matrix3.h"
#include "Math/Matrix4.h"
#include "Math/Quaternion.h"
#include "Math/Random.h"
#include "Math/Transform.h"
#include "Math/Vector2.h"
#include "Math/Vector3.h"
#include "Math/Vector4.h"